keys:
  - &primary age1mvqrpx830w7pk34wasvlc03n0qe85ux2zqx6y7zvu5mycm0tcawq4q6lke
creation_rules:
  - path_reges: secrets/secrets.yaml$ # lol change this
    key_groups:
      - age:
          - *primary
